### PR TITLE
Added filename configuration options

### PR DESCRIPTION
**Pull request by woodyrew**
- Filename patterns
- Permalink styles
- Added option to use template file extension

Could do with date handling but works well so far.

### CODE REVIEW

**Comment by leonderijke** [comment]
What's the status on this? Will it be merged?

**Comment by woodyrew** [comment]
@leonderijke It doesn't seem like this is a high priority for contentful-labs or @madtrick .  You could always bring down my repo and use that instead of the official one.

**Comment by leonderijke** [comment]
Yes indeed, I asked them about in on Twitter: https://twitter.com/contentful/status/621605842077503488

**Comment by grncdr** [comment]
Thanks @woodyrew, thanks for this PR! Regarding the long response, we are in the final stages of hiring a full-time community JS developer, so some of our more popular labs projects should become better supported.

**Comment by woodyrew** [comment]
You're welcome @grncdr. Good to know you're getting on top of the situation. :smile:

**Pull request merged**
